apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env-config
  labels:
    app: {{ .Release.Name }}-nginx
data:
  # 挂载到 Nginx 容器内的测试环境配置文件
  env-config.json: |
    {
      "environment": "{{ .Release.Name }}",
      "status": "healthy"
    }
